config/routes.rb
Rails.application.routes.draw do
  get 'errors/show'

  get 'soeg' => 'search#search'

  get 'information-om-cookies' => 'static_pages#information'

  resources :texts
  get 'danmarkskort' => 'static_pages#danmarkskort'
	get 'not-yet' => 'static_pages#not_yet', as: :not_yet

  post 'sorting-objects' => 'application#sorting_objects'

  devise_for :users, path: '', path_names: { sign_in: 'log-in', sign_up: 'opret-bruger' }

  resources :categories, except: :index
  get '/oversigt' => 'categories#index', as: "oversigt"

  resources :works, except: :index do
    put :sort, on: :collection
    put 'save_overview_img/:image_id' => 'works#save_overview_img', as: :save_overview_img
    member do
      put :sort_images
      get :get_overview_img
      get :new_image
      get :new_image_category
    end
  end
  get 'vaerker/:vaerker_cat' => 'works#index', as: :vaerker

  get 'vaerker/design/:vaerker_cat' => 'works#design_index', as: :vaerker_design

  ### PDFS ###

  resources :pdf_categories, except: [:index] do
    resources :pdfs, except: [:index]
  end

  get "johannes-exners-tekster/vis-alle" => "pdf_categories#index", as: "show_pdf_category"
  get "johannes-exners-tekster/:kategori_id" => "pdf_categories#show_category", as: "show_this_pdf_category"

  ### END PDFS ###

  ### OM ###
  get 'om' => 'about#index', as: "om"
  resources :videos, path: 'om/videoer'
  resources :facts, except: [:show],  path: 'om/facts'
  get 'om/artikler' => 'about#artikler', as: :artikler
  get 'om/tidslinje' => 'about#tidslinje', as: :tidslinje
  ### END OM ###

  #FORSIDE TEKST
  get 'forside/ny-forside-tekst' => 'static_pages#new_frontpage_text', as: :ny_forside_tekst
  get 'forside/rediger-forside-tekst/:text_id' => 'static_pages#edit_frontpage_text', as: :rediger_forside_tekst
  post 'forside/opret-forside-tekst' => 'static_pages#create_frontpage_text', as: :opret_forside_tekst
  patch 'forside/opdater-tekst/:id' => 'static_pages#update_frontpage_text', as: :opdater_forside_tekst

  root 'static_pages#frontpage'
  # END FORSIDE TEKST
	# error pages
  %w( 404 422 500 503 ).each do |code|
    get code, :to => "errors#show", :code => code
  end
end

app/models/category.rb
class Category < ApplicationRecord
	extend FriendlyId
	mount_uploader :image, CategoryUploader

	friendly_id :name, use: :slugged

	has_many :works, -> { order(:position) }

	default_scope { order(:position) }

	def works_sort
		works.order(position: :asc)
	end

	def self.sort_by_position
		order(position: :asc)
	end

end

app/models/fact.rb
class Fact < ApplicationRecord
  validates_presence_of :title, :text
end

app/models/frontpage_text.rb
class FrontpageText < ApplicationRecord

end

app/models/image.rb
class Image < ApplicationRecord
	mount_uploader :image, ImageUploader
	belongs_to :image_category
	#scope
	default_scope { order(:position) }
	scope :published, -> { where(draft: false) }
end

app/models/image_category.rb
class ImageCategory < ApplicationRecord
	validates_presence_of :name
	belongs_to :work
	has_many :images
	accepts_nested_attributes_for :images, allow_destroy: true

	default_scope { order(:position) }
end

app/models/info.rb
class Info < ApplicationRecord
	belongs_to :work
end

app/models/map_info.rb
class MapInfo < ApplicationRecord
  belongs_to :work
end

app/models/pdf.rb
class Pdf < ApplicationRecord
	mount_uploader :image, PdfImageUploader
	extend FriendlyId

	friendly_id :title, use: [:slugged, :finders]
	belongs_to :pdf_category
  default_scope { order(date: :asc)  }

end

app/models/pdf_category.rb
class PdfCategory < ApplicationRecord
	extend FriendlyId
	friendly_id :title, use: [:slugged]

	has_many :pdfs
	scope :not_about, -> { where.not(id: [1, 2]).order(position: :asc) }
end

app/models/text.rb
class Text < ApplicationRecord

end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/video.rb
class Video < ApplicationRecord
  mount_uploader :link_image, LinkImageUploader
  validates_presence_of :title
  default_scope { order(year: :asc) }
end

app/models/work.rb
class Work < ActiveRecord::Base

	extend FriendlyId
	friendly_id :name, use: :slugged
	mount_uploader :overview_img, OverviewUploader
	belongs_to :category
	has_many :infos
	has_many :image_categories, -> { order(position: :asc) }
	has_many :images, through: :image_categories
	has_one :map_info, dependent: :destroy
	# accepts_nested_attributes_for :map_info, reject_if: proc { |attributes| attributes['lat_x'].blank? }
	accepts_nested_attributes_for :map_info, allow_destroy: true
	accepts_nested_attributes_for :image_categories, allow_destroy: true
	accepts_nested_attributes_for :infos, allow_destroy: true

	default_scope { order(position: :asc)}

end

app/controllers/pdf_categories_controller.rb
class PdfCategoriesController < ApplicationController
	before_action :authenticate_user!, except: :show_category
	layout "works"

	def show_category
		if ["andres-tekster-andre-sprog", "andres-tekster"].include? params[:kategori_id] # Hvis det er andres artikler
			redirect_to artikler_path()
		else
			@breadcrumb_parent = {title: "Johannes' tekster", path: "show_this_pdf_category_path('0')"}
			if params[:kategori_id] == "0" && !Text.last.nil? # Intro og tekst er oprettet
				@pdf_categories = PdfCategory.not_about
				@cat_headline = "Intro"
				@text = Text.last
				@breadcrumb_child = {title: @cat_headline, path: "show_this_pdf_category_path('0')"}
        @meta_title = meta_title "Johannes' tekster"
			else
				@pdf_cat = params[:kategori_id] == "0" ? PdfCategory.first : PdfCategory.friendly.find(params[:kategori_id])
				@pdf_categories = PdfCategory.not_about
				@pdfs = user_signed_in? ? @pdf_cat.pdfs : @pdf_cat.pdfs.where.not(show_not: true) # Hvis du er logget ind, så vis alle pdf'er
				@cat_headline = @pdf_cat.title
				@breadcrumb_child = {title: @cat_headline, path: "show_this_pdf_category_path('#{@pdf_cat.slug}')"}
        @meta_title = meta_title @cat_headline
			end
			render 'index'
		end
	end

end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/errors_helper.rb
module ErrorsHelper
end

app/helpers/facts_helper.rb
module FactsHelper
end

app/helpers/pdf_categories_helper.rb
module PdfCategoriesHelper
	

end

app/helpers/pdfs_helper.rb
module PdfsHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/texts_helper.rb
module TextsHelper
end

app/helpers/videoes_helper.rb
module VideoesHelper
end

app/helpers/works_helper.rb
module WorksHelper

  def logged_in_work_helper
    button = (link_to "Rediger værk", edit_work_path(@work), class: "btn btn-secondary")
    content_tag :div, button, class: "col-lg-12"
  end

end

app/views/pdf_categories/_pdf.html.erb
<div class=" col-sm-4 col-6 col-lg-3 pdf <%= 'pdf-not-shown' if pdf.show_not %>">
  <% if pdf.show_not %>
    <small>Bliver ikke vist til besøgende</small>
  <% end%>
    <%# <%= link_to pdf.file, target: "_blank" do %1> %>
    <%= link_to pdf_category_pdf_path(pdf.pdf_category, pdf)  do %>
      <%= content_tag :div, (image_tag pdf.image.thumb.url), class:"img-wrapper" unless pdf.image.thumb.url.nil? %>
      <p class="pdf-title">
        <%= pdf.opening_year unless pdf.opening_year.nil? %><br>
        <%= pdf.title %>
      </p>
    <% end %>
  <%= link_to "Rediger", edit_pdf_category_pdf_path(pdf.pdf_category, pdf), class: "btn btn-secondary" if user_signed_in? %>
</div>

app/views/pdf_categories/edit.html.erb
<h1>PdfCategories#edit</h1>
<p>Find me in app/views/pdf_categories/edit.html.erb</p>

app/views/pdf_categories/hallo.html.erb
<div class="row">
	<% @pdf_categories.each do |cat| %>
	<div class="col-md-6 col-sm-4 pdf-cat ">
		<%= link_to show_this_pdf_category_path(cat.id), remote: true do %>
		<h4 class="text-center"><%= cat.title %></h4>
		<% end %>
	</div>

	<% end %>

	<div class="col-sm-12"></div>
	<div class="pdf-works row">
		<%= render partial: "pdf", collection: @pdfs %>
	</div>

</div><!-- row -->

app/views/pdf_categories/index.html.erb
<script>
	$(document).ready(function() {
		$("[data-type='button']").click(function() {
		  $(this).toggleClass("active");
		  
			target_class = $(this).data('target');
			$("." + target_class).slideToggle(400);
		});
	});
</script>
<div class="row remove-margin">
	<div class="col-md-3" id="pdfWrapper">
		<div class="fixme" id="pdfScroll"><!-- add pdf-works when scrolling -->
			<h2 class="text-center fixme-button" data-target="pdf-cat-inner" data-type="button">Se kategorier</h2>
			<div class="pdf-cat-inner"">
				<%= link_to "Intro", show_this_pdf_category_path(0), class: "nav-link #{'active' unless @text.nil? }" %>
				<% @pdf_categories.each do |cat| %>
					<% unless @pdf_cat.nil? %>
						<%= link_to cat.title, show_this_pdf_category_path(cat.friendly_id), class: "nav-link #{'active' if @pdf_cat.id == cat.id}" %>
					<% else %>
						<%= link_to cat.title, show_this_pdf_category_path(cat.friendly_id), class: "nav-link"  %>
					<% end %>
				<% end %>
			</div>
			<div class="pdf-cat-inner">
				<%= link_to "Til andres tekster &#8594;".html_safe, artikler_path(), class: "nav-link andres-tekster" %>
			</div>
		</div>
	</div>
	<% if @pdfs.blank? && @text.present? %>
		<div class="col-md-9 pdf-row row">
			<%= content_tag :h2, @cat_headline, class: "col-12 py-4 pt-1 pdf-cat-headline" unless @cat_headline.nil? %>
			<%= @text.text.html_safe %><br>
		</div>
		<%= link_to "Rediger Intro tekst", edit_text_path(@text.id), class: "btn btn-secondary" if user_signed_in? %>
	<% else %>
		<div class="col-md-9 pdf-row row">
			<%= content_tag :h2, @cat_headline, class: "col-12 py-4 pt-1 pdf-cat-headline" unless @cat_headline.nil? %>
			<%= render partial: "pdf", collection: @pdfs %>
		</div>
	<% end %> 
</div>
<%= link_to "Opret ny intro tekst", new_text_path(), class: "btn btn-secondary" if user_signed_in? && @text.nil? %>
<script>
var fixmeTop = $('.fixme').offset().top;       // get initial position of the element
$(window).scroll(function() {                  // assign scroll event listener
var currentScroll = $(window).scrollTop() + 18; // get current position
if (currentScroll >= fixmeTop) {           // apply position: fixed if you
width = $("#pdfWrapper").width();
left = $("#pdfWrapper").offset().left;
$('.fixme').css({                      // scroll to that element or below it
position: 'fixed',
top: '18px',
left: left + 'px',
width: width + 'px'
});
} else {                                   // apply position: static
$('.fixme').css({                      // if you scroll above it
position: 'static'
});
}

});</script>

app/views/pdf_categories/new.html.erb
<h1>PdfCategories#new</h1>
<p>Find me in app/views/pdf_categories/new.html.erb</p>

app/views/pdf_categories/show.html.erb
<div style="float: left; width: 33%; height: 30px; text-align: center">
	<%= link_to truncate(@prev_pdf.title, length: 45), pdf_category_path(@prev_pdf) %>
</div>
<div style="float: left; width: 33%; height: 30px; text-align: center">
	<%= link_to @pdf_category.title, show_pdf_category_path(@pdf_category.id) %>
</div>
<div style="float: left; width: 33%; height: 30px; text-align: center">
	<%= link_to truncate(@next_pdf.title, length: 45), pdf_category_path(@next_pdf) %>
</div>

<iframe src="<%= @pdf_url %>" style="left: 0; border: 0; width: 100%; height: 100%; position: absolute; top: 30px" frameborder="0" scrolling="no" crossorigin="anonymous">
</iframe> 

app/views/pdf_categories/show_category.js.erb
$(".pdf-works").html("<%= escape_javascript( render partial: "pdf", collection: @pdfs ) %>");