config/routes.rb
Rails.application.routes.draw do
  get 'errors/show'

  get 'soeg' => 'search#search'

  get 'information-om-cookies' => 'static_pages#information'

  resources :texts
  get 'danmarkskort' => 'static_pages#danmarkskort'
	get 'not-yet' => 'static_pages#not_yet', as: :not_yet

  post 'sorting-objects' => 'application#sorting_objects'

  devise_for :users, path: '', path_names: { sign_in: 'log-in', sign_up: 'opret-bruger' }

  resources :categories, except: :index
  get '/oversigt' => 'categories#index', as: "oversigt"

  resources :works, except: :index do
    put :sort, on: :collection
    put 'save_overview_img/:image_id' => 'works#save_overview_img', as: :save_overview_img
    member do
      put :sort_images
      get :get_overview_img
      get :new_image
      get :new_image_category
    end
  end
  get 'vaerker/:vaerker_cat' => 'works#index', as: :vaerker

  get 'vaerker/design/:vaerker_cat' => 'works#design_index', as: :vaerker_design

  ### PDFS ###

  resources :pdf_categories, except: [:index] do
    resources :pdfs, except: [:index]
  end

  get "johannes-exners-tekster/vis-alle" => "pdf_categories#index", as: "show_pdf_category"
  get "johannes-exners-tekster/:kategori_id" => "pdf_categories#show_category", as: "show_this_pdf_category"

  ### END PDFS ###

  ### OM ###
  get 'om' => 'about#index', as: "om"
  resources :videos, path: 'om/videoer'
  resources :facts, except: [:show],  path: 'om/facts'
  get 'om/artikler' => 'about#artikler', as: :artikler
  get 'om/tidslinje' => 'about#tidslinje', as: :tidslinje
  ### END OM ###

  #FORSIDE TEKST
  get 'forside/ny-forside-tekst' => 'static_pages#new_frontpage_text', as: :ny_forside_tekst
  get 'forside/rediger-forside-tekst/:text_id' => 'static_pages#edit_frontpage_text', as: :rediger_forside_tekst
  post 'forside/opret-forside-tekst' => 'static_pages#create_frontpage_text', as: :opret_forside_tekst
  patch 'forside/opdater-tekst/:id' => 'static_pages#update_frontpage_text', as: :opdater_forside_tekst

  root 'static_pages#frontpage'
  # END FORSIDE TEKST
	# error pages
  %w( 404 422 500 503 ).each do |code|
    get code, :to => "errors#show", :code => code
  end
end

app/models/category.rb
class Category < ApplicationRecord
	extend FriendlyId
	mount_uploader :image, CategoryUploader

	friendly_id :name, use: :slugged

	has_many :works, -> { order(:position) }

	default_scope { order(:position) }

	def works_sort
		works.order(position: :asc)
	end

	def self.sort_by_position
		order(position: :asc)
	end

end

app/models/fact.rb
class Fact < ApplicationRecord
  validates_presence_of :title, :text
end

app/models/frontpage_text.rb
class FrontpageText < ApplicationRecord

end

app/models/image.rb
class Image < ApplicationRecord
	mount_uploader :image, ImageUploader
	belongs_to :image_category
	#scope
	default_scope { order(:position) }
	scope :published, -> { where(draft: false) }
end

app/models/image_category.rb
class ImageCategory < ApplicationRecord
	validates_presence_of :name
	belongs_to :work
	has_many :images
	accepts_nested_attributes_for :images, allow_destroy: true

	default_scope { order(:position) }
end

app/models/info.rb
class Info < ApplicationRecord
	belongs_to :work
end

app/models/map_info.rb
class MapInfo < ApplicationRecord
  belongs_to :work
end

app/models/pdf.rb
class Pdf < ApplicationRecord
	mount_uploader :image, PdfImageUploader
	extend FriendlyId

	friendly_id :title, use: [:slugged, :finders]
	belongs_to :pdf_category
  default_scope { order(date: :asc)  }

end

app/models/pdf_category.rb
class PdfCategory < ApplicationRecord
	extend FriendlyId
	friendly_id :title, use: [:slugged]

	has_many :pdfs
	scope :not_about, -> { where.not(id: [1, 2]).order(position: :asc) }
end

app/models/text.rb
class Text < ApplicationRecord

end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/video.rb
class Video < ApplicationRecord
  mount_uploader :link_image, LinkImageUploader
  validates_presence_of :title
  default_scope { order(year: :asc) }
end

app/models/work.rb
class Work < ActiveRecord::Base

	extend FriendlyId
	friendly_id :name, use: :slugged
	mount_uploader :overview_img, OverviewUploader
	belongs_to :category
	has_many :infos
	has_many :image_categories, -> { order(position: :asc) }
	has_many :images, through: :image_categories
	has_one :map_info, dependent: :destroy
	# accepts_nested_attributes_for :map_info, reject_if: proc { |attributes| attributes['lat_x'].blank? }
	accepts_nested_attributes_for :map_info, allow_destroy: true
	accepts_nested_attributes_for :image_categories, allow_destroy: true
	accepts_nested_attributes_for :infos, allow_destroy: true

	default_scope { order(position: :asc)}

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
	before_action :authenticate_user!, except: [:information, :danmarkskort, :frontpage, :about, :get_geo_json]
	layout "works", except: [:frontpage]

  def information
    @meta_title = meta_title "Cookie information"
  end

	def danmarkskort
    @meta_title = meta_title "Danmarkskort"
    @meta_description = "Danmarkskortet er en oversigt med oplysninger om bygningernes beliggenhed, til studier og excursioner."
		if params[:id].nil?
			data = get_geo_json MapInfo.all
			@no_popup = true
		else #
			map_info = Work.find(params[:id]).map_info
			arr = []
			arr << map_info
			arr += MapInfo.where.not(id: map_info.id)
			data = get_geo_json arr
			@breadcrumb_child = {title: map_info.title, path: "danmarkskort_path(#{map_info.id})"}
		end
			@breadcrumb_parent = {title: "Danmarkskort", path: "danmarkskort_path()"}
		@json_data = data.to_json
	end


	def frontpage
    @meta_title = meta_title "Egen hjemmeside"
		if FrontpageText.all.any?
			@text = FrontpageText.last
		else
			@text = nil
		end
			render layout: "frontpage"
	end

	def new_frontpage_text
		@text = FrontpageText.new()
	end

	def edit_frontpage_text
		@text = FrontpageText.find(params[:text_id])
	end

	def create_frontpage_text
		@text = FrontpageText.new(frontpage_text_params)
		if @text.save
			redirect_to root_path
		else
			redirect_to root_path, notice: "Noget gik galt!"
		end
	end

	def update_frontpage_text
		@text = FrontpageText.find(params[:id])
		if @text.update(frontpage_text_params)
			redirect_to root_path
		else
			redirect_to root_path, notice: "Noget gik galt!"
		end
	end

	private

	def get_geo_json records
		new_data = records.map do |f|
			next if f.lat_y.blank? || f.lat_x.blank?
			{
				type: "Feature",
				"geometry": {
					"type": "Point",
					"coordinates": [f.lat_y,f.lat_x]
				},
				"properties": {
					"id": f.id,
					"description": f.text,
					"title": f.title,
					"sagsnr": f.sagsnr,
					"link": f.link,
					"address": f.address
				}
			}
		end
		return new_data.compact # remove nil objects made by next
	end

	def frontpage_text_params
		params.require(:frontpage_text).permit(:text)
	end

end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/errors_helper.rb
module ErrorsHelper
end

app/helpers/facts_helper.rb
module FactsHelper
end

app/helpers/pdfs_helper.rb
module PdfsHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/texts_helper.rb
module TextsHelper
end

app/helpers/works_helper.rb
module WorksHelper

  def logged_in_work_helper
    button = (link_to "Rediger værk", edit_work_path(@work), class: "btn btn-secondary")
    content_tag :div, button, class: "col-lg-12"
  end

end

app/views/static_pages/danmarkskort.html.erb
<% content_for :custom_calls do %>
	<link rel="stylesheet" href="https://unpkg.com/leaflet@1.2.0/dist/leaflet.css"
												integrity="sha512-M2wvCLH6DSRazYeZRIm1JnYyh22purTM+FDB5CsyxtQJYeKq83arPe5wgbNmcFXGqiSH2XR8dT/fJISVA1r/zQ=="
						crossorigin=""/>

	<script src="https://unpkg.com/leaflet@1.2.0/dist/leaflet.js"
		integrity="sha512-lInM/apFSqyy1o6s89K4iQUKg6ppXEgsVxT35HbzUupEVRh2Eu9Wdl4tHj7dZO0s1uvplcYGmt3498TtHq+log=="
	 crossorigin=""></script>

<% end %>
<h2 class="py4 text-center">Danmarkskort</h2>
<%= hidden_field_tag :email, "peter@hej.com" %>
<p class="text-center hidden-md-up">Til mobilbrugere: Zoom på kortet ved at trække to fingre fra hinanden, træk i kortet med to fingre for at flytte visningen og scroll op og ned på hjemmesiden med én finger.</p>
<div id="danmarkskort">

</div>

<script>

	var work_id = decodeURIComponent((new RegExp('[?|&]' + "id" + '=' + '([^&;]+?)(&|#|;|$)').exec(location.search) || [null, ''])[1].replace(/\+/g, '%20')) || null;

var map_data = <%= @json_data.html_safe %>;
var mymap = L.map('danmarkskort', {
	scrollWheelZoom: true, // Så man ikke kan scrolle med musen!
  touchZoom: true,
  dragging: !L.Browser.mobile
}).setView([55.861948, 10.624085], 7.6);

L.tileLayer('https://api.tiles.mapbox.com/v4/{id}/{z}/{x}/{y}.png?access_token={accessToken}', {
	maxZoom: 18,
	id: 'mapbox.streets',
	accessToken: 'pk.eyJ1IjoicGV0ZXJob2VqbHVuZCIsImEiOiJjamM2YnRmOWYxZjdnMzNtbWdkYnJyZHpuIn0.YA23PjVD-QDVseZEEVTflQ'
}).addTo(mymap);

var geoJSONLayers = L.geoJSON(map_data, { }).addTo(mymap);

if (work_id) {
	geoJSONLayers.bindPopup(function (layer) {
		link = (layer.feature.properties.link != null) ? "<br><a href='" + layer.feature.properties.link + "'>Gå til</a>" : ""
		sagsnr = (layer.feature.properties.sagsnr != null) ? "<br>Sagsnr: " + layer.feature.properties.sagsnr : ""
		return "<h3 class='min-popup-" + layer.feature.properties.id + "'>" + layer.feature.properties.title + "</h3>"
			+ "<p>" + layer.feature.properties.description + "<br>" + 
			"Adresse: " + layer.feature.properties.address +  sagsnr + "<br>"
			+ link + "</p>";
	}).openPopup().addTo(mymap);
} else {
	geoJSONLayers.bindPopup(function (layer) {
		link = (layer.feature.properties.link != null) ? "<br><a href='" + layer.feature.properties.link + "'>Gå til</a>" : ""
		sagsnr = (layer.feature.properties.sagsnr != null) ? "<br>Sagsnr: " + layer.feature.properties.sagsnr : ""
		return "<h3 class='min-popup-" + layer.feature.properties.id + "'>" + layer.feature.properties.title + "</h3>"
			+ "<p>" + layer.feature.properties.description + "<br>" + 
			"Adresse: " + layer.feature.properties.address +  sagsnr + "<br>"
			+ link + "</p>";
	}).addTo(mymap);
}

</script>

app/views/static_pages/edit_frontpage_text.html.erb
<%= tinymce_assets %>
<%= tinymce %>

<div class="row">
  <div class="offset-lg-2 col-lg-8">
    <%= form_for @text, url: opdater_forside_tekst_path(@text.id) do |f| %>

      <div class="form-fields">
        <%= f.label "Tekst" %>
        <%= f.text_area :text, cols: 40, rows: 20, class: "tinymce" %>
      </div>

      <hr>

      <%= f.submit "Gem tekst", class: "btn btn-primary" %>
    <% end %>

  </div>
</div>

app/views/static_pages/frontpage.html.erb
<div class="indexbackground"><!-- billede -->
  <%= image_tag 'inger-og-johannes-exner.jpg', id: "hiddenImage", class: "hide-it" %>

  <%# <img src="<%= image_url('inger-og-johannes-exner.jpg') %1>" id="hiddenImage" hidden /> %>
</div>
  <script>
    $("#hiddenImage").on('load', function() {
      image_src = $(this).attr('src');
      $(".indexbackground").css({
        "background-image": 'url(' + image_src + ')',
        "background-size": 'cover' // The load icon shoudn't cover the while screen
      });
    });
  </script>
	<div class="oversigt-button-wrapper hidden-md-up"><%= link_to "Gå til oversigt &#8594;".html_safe, oversigt_path(), class: "oversigt-button" %></div>
<div class="row indexwrapper overskrift-wrapper remove-margin">
  <div class="col-md-12 frontpage-ark">
    <div class="h4 masthead-overskrift-ark">Arkitekterne</div><div class="h1 masthead-overskrift">Inger og Johannes Exner</div>
    <p class="text-center button-read-more white hidden-md-down">Hvorfor denne hjemmeside? Læs mere <%= fa_icon "angle-down" %></p> 
  </div>
</div><!-- indexwrapper -->
<div class="row remove-margin">
  <div class="offset-lg-3 col-lg-6 offset-md-1 col-md-10 front-page-text">
    <% if @text.nil? %>
			<%= link_to "Opret tekst", ny_forside_tekst_path(), class: "btn btn-secondary" if user_signed_in? %>
    <% else %>
      <%= link_to "Rediger teksten", rediger_forside_tekst_path(@text.id), class: "btn btn-secondary" if user_signed_in? %>

      <%= @text.text.html_safe %>
    <% end %> 
  </div>
  <div class="col-lg-3 float-left to-oversigt">
    <%= link_to oversigt_path, class: "float-right affix" do %>
      <div class="button"></div>
    <% end %>
  </div>

</div><!-- row -->
<!-- trekanten skifter farve -->
<script type="text/javascript">
  $(document).ready(function() {
    $(".button-read-more").click(function (){
      $('html, body').animate({
        scrollTop: $(".front-page-text").offset().top
      }, 500);
    });
  })
$(window).scroll(function () {
  if ($(".button").offset().top > ($(".front-page-text").offset().top)) {
    $(".button").addClass('black-trans');
  } else {
    $(".button").removeClass('black-trans');
  }	
});
</script>

app/views/static_pages/index.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0" />

	<title>I&J EXNER</title>

	<%= stylesheet_link_tag    "application" %>
	<%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
	<%= csrf_meta_tags %>
</head>

<body>
	<div class="indexwrapper">
		<div class="indexbackground">
		</div>
		<div class="indexareatext">
			<div class="left leftindex">
				<h4 class="text-center">Arkitekterne</h4>
				<h1 class="text-center">Inger og Johannes Exner</h1>
			</div>
			<div class="left middleindex">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quia quo pariatur ipsa culpa deserunt, obcaecati alias eveniet molestiae dolorem est ad repudiandae atque sunt optio aliquid. Quam vero ipsam fugit!
				Lorem ipsum dolor sit amet, consectetur adipisicing elit. Maxime voluptas amet culpa, dolorem facere autem veniam, odit id vel, velit quidem architecto nisi, illum esse magnam consequuntur maiores dolorum nihil.</div>
				<div class="left rightindex">
					<%= link_to kategori_oversigt_path(Category.first) do %>
					<div data-toggler data-animate="fade-in fade-out" class="button"><span class="kunpaamobilskaerm">Gå videre til oversigt</span></div>
					<% end %>
				</div>
			</div>
		</div>
	</body>
</body>
</html>

app/views/static_pages/information.html.erb
<h2> Cookie- og privatlivspolitik </h2>

<br>
<br>
<h3> Introduktion </h3>

<p>
  Når du besøger vores website indsamles der oplysninger om dig. Hvis du ikke ønsker, at der indsamles oplysninger, bør du slette dine cookies (<a href="http://minecookies.org/cookiehandtering/" target="_blank">se vejledning</a>) og undlade videre brug af websitet. Nedenfor har vi uddybet, hvilke informationer der indsamles, deres formål og hvilke tredjeparter, der har adgang til dem.
</p>

<br>
<br>
<h3> Cookies </h3>

<p>
  Websitet anvender ”cookies”, der er en tekstfil, som gemmes på din computer, mobil el. tilsvarende. Cookies kan ikke indeholde skadelig kode som f.eks. virus.
</p>

<p>
  Det er muligt at slette eller blokere for cookies. Se vejledning: <a href="http://minecookies.org/cookiehandtering">http://minecookies.org/cookiehandtering</a>
</p>

<p>
  Websitet indeholder cookies fra tredjeparter, der i varierende omfang kan omfatte. 
</p>

<table class="table">
  <thead>
    <tr>
      <th scope="col">Cookiens navn</th>
      <th scope="col">Udløbstid</th>
      <th scope="col">Funktion</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td> _ga	</td>
      <td> 2 years	</td>
      <td> Used to distinguish users.  </td>
    </tr>
    <tr>
      <td> _gid	</td>
      <td>24 hours</td>
      <td> Used to distinguish users.  </td>
    </tr>
    <tr>
      <td> _gat	</td>
      <td>1 minute</td>
      <td> Used to throttle request rate.  </td>
    </tr>
  </tbody>
</table>
<i>Informationerne er hentet på <a href="https://developers.google.com/analytics/devguides/collection/analyticsjs/cookie-usage">Google Developer</a></i>

<br>
<br>
<br>
<br>
<h3> Generelt </h3>

<p>
  Personoplysninger er alle slags informationer, der i et eller andet omfang kan henføres til dig. Når du benytter vores website indsamler og behandler vi en række sådanne informationer. Det sker f.eks. ved alm. tilgang af indhold.
</p>

<p>
  Vi indsamler og behandler typisk følgende typer af oplysninger: Et unikt ID og tekniske oplysninger om din computer, tablet eller mobiltelefon, dit IP-nummer, geografisk placering, samt hvilke sider du klikker på (interesser).
</p>

<br>
<br>
<h3> Sikkerhed </h3>

<p>
  Vi har truffet tekniske og organisatoriske foranstaltninger mod, at dine oplysninger hændeligt eller ulovligt bliver slettet, offentliggjort, fortabt, forringet eller kommer til uvedkommendes kendskab, misbruges eller i øvrigt behandles i strid med lovgivningen.
</p>

<br>
<br>
<h3> Periode for opbevaring </h3>

<p>
  Oplysningerne opbevares i det tidsrum, der er tilladt i henhold til lovgivningen, og vi sletter dem, når de ikke længere er nødvendige. Perioden afhænger af karakteren af oplysningen og baggrunden for opbevaring. Det er derfor ikke muligt at angive en generel tidsramme for, hvornår informationer slettes.
</p>

<br>
<br>
<h3>
  Videregivelse af oplysninger
</h3>

<p>
  Data om din brug af websitet, hvilke annoncer, du modtager og evt. klikker på, geografisk placering, køn og alderssegment m.v. videregives til tredjeparter i det omfang disse oplysninger er kendt. Du kan se hvilke tredjeparter, der er tale om, i afsnittet om ”Cookies” ovenfor.
</p>

<p>
  Vi benytter herudover en række tredjeparter til opbevaring og behandling af data. Disse behandler udelukkende oplysninger på vores vegne og må ikke anvende dem til egne formål.
</p>

<br>
<br>
<h3> Indsigt og klager </h3>

<p>
  Du har ret til at få oplyst, hvilke personoplysninger, vi behandler om dig. Du kan desuden til enhver tid gøre indsigelse mod, at oplysninger anvendes. Du kan også tilbagekalde dit samtykke til, at der bliver behandlet oplysninger om dig. Hvis de oplysninger, der behandles om dig, er forkerte har du ret til at de bliver rettet eller slettet. Henvendelse herom kan ske til: kontakt@hilsen.it. Hvis du vil klage over vores behandling af dine personoplysninger, har du også mulighed for at tage kontakt til Datatilsynet.
</p>

<br>
<br>
<p>
  Hjemmesidens ansvarlige er:<br>
  
  Hilsen IT <br>
  Telefon: 42645898 <br>
  Email: kontakt@hilsen.it <br>
</p>

app/views/static_pages/new_frontpage_text.html.erb
<%= tinymce %>
<%= tinymce_assets %>


<div class="row">
	<div class="offset-lg-2 col-lg-8">
		<%= form_for @text, url: opret_forside_tekst_path() do |f| %>

		<div class="form-fields">
			<%= f.label "Tekst" %>
			<%= f.text_area :text, cols: 40, rows: 20, class: "tinymce", id:  %>
		</div>

		<hr>

		<%= f.submit "Gem tekst", class: "btn btn-primary" %>
		<% end %>

	</div>
</div>