config/routes.rb
Rails.application.routes.draw do
  get 'errors/show'

  get 'soeg' => 'search#search'

  get 'information-om-cookies' => 'static_pages#information'

  resources :texts
  get 'danmarkskort' => 'static_pages#danmarkskort'
	get 'not-yet' => 'static_pages#not_yet', as: :not_yet

  post 'sorting-objects' => 'application#sorting_objects'

  devise_for :users, path: '', path_names: { sign_in: 'log-in', sign_up: 'opret-bruger' }

  resources :categories, except: :index
  get '/oversigt' => 'categories#index', as: "oversigt"

  resources :works, except: :index do
    put :sort, on: :collection
    put 'save_overview_img/:image_id' => 'works#save_overview_img', as: :save_overview_img
    member do
      put :sort_images
      get :get_overview_img
      get :new_image
      get :new_image_category
    end
  end
  get 'vaerker/:vaerker_cat' => 'works#index', as: :vaerker

  get 'vaerker/design/:vaerker_cat' => 'works#design_index', as: :vaerker_design

  ### PDFS ###

  resources :pdf_categories, except: [:index] do
    resources :pdfs, except: [:index]
  end

  get "johannes-exners-tekster/vis-alle" => "pdf_categories#index", as: "show_pdf_category"
  get "johannes-exners-tekster/:kategori_id" => "pdf_categories#show_category", as: "show_this_pdf_category"

  ### END PDFS ###

  ### OM ###
  get 'om' => 'about#index', as: "om"
  resources :videos, path: 'om/videoer'
  resources :facts, except: [:show],  path: 'om/facts'
  get 'om/artikler' => 'about#artikler', as: :artikler
  get 'om/tidslinje' => 'about#tidslinje', as: :tidslinje
  ### END OM ###

  #FORSIDE TEKST
  get 'forside/ny-forside-tekst' => 'static_pages#new_frontpage_text', as: :ny_forside_tekst
  get 'forside/rediger-forside-tekst/:text_id' => 'static_pages#edit_frontpage_text', as: :rediger_forside_tekst
  post 'forside/opret-forside-tekst' => 'static_pages#create_frontpage_text', as: :opret_forside_tekst
  patch 'forside/opdater-tekst/:id' => 'static_pages#update_frontpage_text', as: :opdater_forside_tekst

  root 'static_pages#frontpage'
  # END FORSIDE TEKST
	# error pages
  %w( 404 422 500 503 ).each do |code|
    get code, :to => "errors#show", :code => code
  end
end

app/models/category.rb
class Category < ApplicationRecord
	extend FriendlyId
	mount_uploader :image, CategoryUploader

	friendly_id :name, use: :slugged

	has_many :works, -> { order(:position) }

	default_scope { order(:position) }

	def works_sort
		works.order(position: :asc)
	end

	def self.sort_by_position
		order(position: :asc)
	end

end

app/models/fact.rb
class Fact < ApplicationRecord
  validates_presence_of :title, :text
end

app/models/frontpage_text.rb
class FrontpageText < ApplicationRecord

end

app/models/image.rb
class Image < ApplicationRecord
	mount_uploader :image, ImageUploader
	belongs_to :image_category
	#scope
	default_scope { order(:position) }
	scope :published, -> { where(draft: false) }
end

app/models/image_category.rb
class ImageCategory < ApplicationRecord
	validates_presence_of :name
	belongs_to :work
	has_many :images
	accepts_nested_attributes_for :images, allow_destroy: true

	default_scope { order(:position) }
end

app/models/info.rb
class Info < ApplicationRecord
	belongs_to :work
end

app/models/map_info.rb
class MapInfo < ApplicationRecord
  belongs_to :work
end

app/models/pdf.rb
class Pdf < ApplicationRecord
	mount_uploader :image, PdfImageUploader
	extend FriendlyId

	friendly_id :title, use: [:slugged, :finders]
	belongs_to :pdf_category
  default_scope { order(date: :asc)  }

end

app/models/pdf_category.rb
class PdfCategory < ApplicationRecord
	extend FriendlyId
	friendly_id :title, use: [:slugged]

	has_many :pdfs
	scope :not_about, -> { where.not(id: [1, 2]).order(position: :asc) }
end

app/models/text.rb
class Text < ApplicationRecord

end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/video.rb
class Video < ApplicationRecord
  mount_uploader :link_image, LinkImageUploader
  validates_presence_of :title
  default_scope { order(year: :asc) }
end

app/models/work.rb
class Work < ActiveRecord::Base

	extend FriendlyId
	friendly_id :name, use: :slugged
	mount_uploader :overview_img, OverviewUploader
	belongs_to :category
	has_many :infos
	has_many :image_categories, -> { order(position: :asc) }
	has_many :images, through: :image_categories
	has_one :map_info, dependent: :destroy
	# accepts_nested_attributes_for :map_info, reject_if: proc { |attributes| attributes['lat_x'].blank? }
	accepts_nested_attributes_for :map_info, allow_destroy: true
	accepts_nested_attributes_for :image_categories, allow_destroy: true
	accepts_nested_attributes_for :infos, allow_destroy: true

	default_scope { order(position: :asc)}

end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/errors_helper.rb
module ErrorsHelper
end

app/helpers/facts_helper.rb
module FactsHelper
end

app/helpers/pdfs_helper.rb
module PdfsHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/texts_helper.rb
module TextsHelper
end

app/helpers/works_helper.rb
module WorksHelper

  def logged_in_work_helper
    button = (link_to "Rediger værk", edit_work_path(@work), class: "btn btn-secondary")
    content_tag :div, button, class: "col-lg-12"
  end

end

app/views/admin/_navbar.html.erb
<!-- Is already secured by user_signed_in? in layout/works -->
<div class="blog-masthead admin-nav">
  <div class="container">
    <nav class="nav">
    	<%= link_to "Opret ny kategori", new_category_path, class: "nav-links btn btn-secondary" %>
    	<%= link_to "Opret nyt værk", new_work_path, class: "nav-links btn btn-secondary" %>
    	<%= link_to "Opret ny artikel", new_pdf_category_pdf_path(1), class: "nav-links btn btn-secondary" %>
      
    	<%= link_to "Log ud", destroy_user_session_path, method: :delete, class: "nav-links btn btn-secondary float-right" %>

    </nav>
  </div>
</div>

app/views/cookies_eu/_consent_banner.html.erb
<% if cookies && cookies['cookie_eu_consented'] != 'true' %>
  <div class="cookies-eu js-cookies-eu">
    <span class="cookies-eu-content-holder"><%= t('cookies_eu.cookies_text').html_safe %></span>
    <span class="cookies-eu-button-holder">
    <button class="cookies-eu-ok js-cookies-eu-ok"> <%= t('cookies_eu.ok') %> </button>
    <% if defined?(link).present? %>
      <a href="<%= link %>" class="cookies-eu-link" target="<%= defined?(target).present? ? target : '' %>"> <%= t('cookies_eu.learn_more') %> </a>
    <% end %>
    </span>
  </div>
<% end %>

app/views/shared/_breadcrumbs.html.erb
<% title_par, title_child =
  helper_breadcrumb_default params if title_par.nil? && title_child.nil? %><!-- overwriting if none of it has been set -->
<% if ["Kirkeinventar", "Nye orgler", "Belysning og andet"].include? title_par[:title] %>
  <%= link_to "Design", vaerker_path('belysning-og-andet', noload: true), class: "nav-link text-center" %> > 
<% elsif ["Håndtegninger", "Fotos", "Livet i tre huse"].include? title_par[:title] %>
  <%= link_to "Om", om_path(), class: "nav-link text-center" %> > 
<% end %>

<%= link_to title_par[:title], eval(title_par[:path]),
  class: "nav-link text-center" unless title_par.nil? %>
<% unless title_child.nil? %>
  > <%= link_to title_child[:title], eval(title_child[:path]), class: "nav-link text-center" %>
<% end %>

app/views/shared/_footer.html.erb
<footer class="text-center copyright pb-2">
  <%= Time.now.year %> Inger og Johannes Exner
</footer>

app/views/shared/_google_analytics.html.erb
<% unless user_signed_in? %><!-- Google Analyics skal ikke tælle besøgende af folk, som er logget ind -->
<!-- Global site tag (gtag.js) - Google Analytics -->
	<script async src="https://www.googletagmanager.com/gtag/js?id=UA-83009453-4"></script>
	<script>
		window.dataLayer = window.dataLayer || [];
		function gtag(){dataLayer.push(arguments);}
		gtag('js', new Date());

		gtag('config', 'UA-83009453-4');
	</script>
<% end %>

app/views/shared/_masthead.html.erb
  <div class="col-lg-12 text-center masthead-overskrift">
    <%= link_to root_path do %>
    <div class="h4 masthead-overskrift-ark">Arkitekterne</div><div class="h1 masthead-overskrift">Inger og Johannes Exner</div>
    <% end %>
  </div>

app/views/shared/_navbar.html.erb
<div class="blog-nav-wrapper">
  <nav class="blog-nav">
    <span class="menu-button" data-button="menu">Menu</span>
    <%= render partial: 'shared/breadcrumbs',
      locals: {title_par: @breadcrumb_parent, title_child: @breadcrumb_child } %>
  </nav>
  <nav class="blog-nav-dropdown hide-it" data-dropdown="menu">
    <% if params[:controller] == "categories" %><!-- hvis det er oversigtssiden, som bliver vist -->
      <%= render partial: 'shared/oversigt_menu' %>
    <% else %>
      <%= render partial: 'shared/normal_menu' %>
    <% end %>
  </nav>
</div>
<script type="text/javascript">
  $(document).ready(function() {
    $("[data-button='menu']").click(function () {
		$(this).toggleClass("active");
    $("[data-dropdown='menu']").slideToggle(400);
  });
  });
</script>

app/views/shared/_normal_menu.html.erb
<div class="normal-menu-wrapper">
  <div class="menu-box oversigt-normal-menu">
    <%= link_to "Oversigt", oversigt_path,
      class: "nav-link #{active_helper? oversigt_path}" 
    %>
		<%= link_to "Danmarkskort", danmarkskort_path(),
			class: "nav-link #{active_helper? danmarkskort_path()}" %>
		<%= link_to "Søg", soeg_path(),
			class: "nav-link #{active_helper? soeg_path()}" %>
  </div>
  <div class="menu-box">
    <%= link_to "Kirker og sognegårde", vaerker_path("Kirker og sognegårde".parameterize),
      class: "nav-link #{active_helper? vaerker_path("Kirker og sognegårde".parameterize)}" 
    %>
    <%= link_to "Koldinghus", vaerker_path("Koldinghus".parameterize),
      class: "nav-link #{active_helper? vaerker_path("Koldinghus".parameterize)}" 
    %>
    <%= link_to "Særlige bygninger", vaerker_path("Særlige bygninger".parameterize),
      class: "nav-link #{active_helper? vaerker_path("Særlige bygninger".parameterize)}" 
    %>
  </div>
  <div class="menu-box">
    <%= link_to "Andre", vaerker_path("Andre".parameterize),
      class: "nav-link #{active_helper? vaerker_path("Andre".parameterize)}" 
    %>
    <%= link_to "Kirkerestaureringer", vaerker_path("Kirkerestaureringer".parameterize),
      class: "nav-link #{active_helper? vaerker_path("Kirkerestaureringer".parameterize)}" 
    %>
    <%= link_to "Design", vaerker_path("belysning-og-andet", noload: "true"),
      class: "nav-link #{active_helper? vaerker_path("Design".parameterize)}" 
    %>
  </div>
  <div class="menu-box">
    <%= link_to "Ikke opført", vaerker_path("Ikke opført".parameterize),
      class: "nav-link #{active_helper? vaerker_path("Ikke opført".parameterize)}" 
    %>
	<%= link_to "Johannes' tekster",  show_this_pdf_category_path('0'),
		class: "nav-link" 
    %>
    <%= link_to "Om", om_path,
      class: "nav-link #{active_helper? om_path}" 
    %>
  </div>
</div>

app/views/shared/_oversigt_menu.html.erb
<div class="oversigt-menu-wrapper">
  <div class="oversigt-om">
    <%= link_to "Oversigt", oversigt_path,
      class: "menu-same-line nav-link #{active_helper? oversigt_path}" 
    %>
		<%= link_to "Danmarkskort", danmarkskort_path(),
			class: "menu-same-line nav-link #{active_helper? danmarkskort_path()}" %>
		<%= link_to "Søg", soeg_path(),
			class: "nav-link #{active_helper? soeg_path()}" %>
  </div>
  <div class="oversigt-menu">
    <%= link_to "Kirker og sognegårde", vaerker_path("Kirker og sognegårde".parameterize),
      class: "nav-link #{active_helper? vaerker_path("Kirker og sognegårde".parameterize)}" 
    %>
    <%= link_to "Koldinghus", vaerker_path("Koldinghus".parameterize),
      class: "nav-link #{active_helper? vaerker_path("Koldinghus".parameterize)}" 
    %>
    <%= link_to "Særlige bygninger", vaerker_path("Særlige bygninger".parameterize),
      class: "nav-link #{active_helper? vaerker_path("Særlige bygninger".parameterize)}" 
    %>
  </div>
  <div class="oversigt-menu ">
    <%= link_to "Andre", vaerker_path("Andre".parameterize),
      class: "nav-link #{active_helper? vaerker_path("Andre".parameterize)}" 
    %>
    <%= link_to "Kirkerestaureringer", vaerker_path("Kirkerestaureringer".parameterize),
      class: "nav-link #{active_helper? vaerker_path("Kirkerestaureringer".parameterize)}" 
    %>
    <%= link_to "Design", vaerker_path("belysning-og-andet", noload: "true"),
      class: "nav-link #{active_helper? vaerker_path("Design".parameterize)}" 
    %>
  </div>
  <div class="oversigt-menu">
    <%= link_to "Ikke opført", vaerker_path("Ikke opført".parameterize),
      class: "nav-link #{active_helper? vaerker_path("Ikke opført".parameterize)}" 
    %>
	<%= link_to "Johannes' tekster", show_this_pdf_category_path('0'),
		class: "nav-link" 
    %>
    <%= link_to "Om", om_path,
      class: "nav-link #{active_helper? om_path}" 
    %>
  </div>
</div>