config/routes.rb
Rails.application.routes.draw do
  get 'errors/show'

  get 'soeg' => 'search#search'

  get 'information-om-cookies' => 'static_pages#information'

  resources :texts
  get 'danmarkskort' => 'static_pages#danmarkskort'
	get 'not-yet' => 'static_pages#not_yet', as: :not_yet

  post 'sorting-objects' => 'application#sorting_objects'

  devise_for :users, path: '', path_names: { sign_in: 'log-in', sign_up: 'opret-bruger' }

  resources :categories, except: :index
  get '/oversigt' => 'categories#index', as: "oversigt"

  resources :works, except: :index do
    put :sort, on: :collection
    put 'save_overview_img/:image_id' => 'works#save_overview_img', as: :save_overview_img
    member do
      put :sort_images
      get :get_overview_img
      get :new_image
      get :new_image_category
    end
  end
  get 'vaerker/:vaerker_cat' => 'works#index', as: :vaerker

  get 'vaerker/design/:vaerker_cat' => 'works#design_index', as: :vaerker_design

  ### PDFS ###

  resources :pdf_categories, except: [:index] do
    resources :pdfs, except: [:index]
  end

  get "johannes-exners-tekster/vis-alle" => "pdf_categories#index", as: "show_pdf_category"
  get "johannes-exners-tekster/:kategori_id" => "pdf_categories#show_category", as: "show_this_pdf_category"

  ### END PDFS ###

  ### OM ###
  get 'om' => 'about#index', as: "om"
  resources :videos, path: 'om/videoer'
  resources :facts, except: [:show],  path: 'om/facts'
  get 'om/artikler' => 'about#artikler', as: :artikler
  get 'om/tidslinje' => 'about#tidslinje', as: :tidslinje
  ### END OM ###

  #FORSIDE TEKST
  get 'forside/ny-forside-tekst' => 'static_pages#new_frontpage_text', as: :ny_forside_tekst
  get 'forside/rediger-forside-tekst/:text_id' => 'static_pages#edit_frontpage_text', as: :rediger_forside_tekst
  post 'forside/opret-forside-tekst' => 'static_pages#create_frontpage_text', as: :opret_forside_tekst
  patch 'forside/opdater-tekst/:id' => 'static_pages#update_frontpage_text', as: :opdater_forside_tekst

  root 'static_pages#frontpage'
  # END FORSIDE TEKST
	# error pages
  %w( 404 422 500 503 ).each do |code|
    get code, :to => "errors#show", :code => code
  end
end

app/models/category.rb
class Category < ApplicationRecord
	extend FriendlyId
	mount_uploader :image, CategoryUploader

	friendly_id :name, use: :slugged

	has_many :works, -> { order(:position) }

	default_scope { order(:position) }

	def works_sort
		works.order(position: :asc)
	end

	def self.sort_by_position
		order(position: :asc)
	end

end

app/models/fact.rb
class Fact < ApplicationRecord
  validates_presence_of :title, :text
end

app/models/frontpage_text.rb
class FrontpageText < ApplicationRecord

end

app/models/image.rb
class Image < ApplicationRecord
	mount_uploader :image, ImageUploader
	belongs_to :image_category
	#scope
	default_scope { order(:position) }
	scope :published, -> { where(draft: false) }
end

app/models/image_category.rb
class ImageCategory < ApplicationRecord
	validates_presence_of :name
	belongs_to :work
	has_many :images
	accepts_nested_attributes_for :images, allow_destroy: true

	default_scope { order(:position) }
end

app/models/info.rb
class Info < ApplicationRecord
	belongs_to :work
end

app/models/map_info.rb
class MapInfo < ApplicationRecord
  belongs_to :work
end

app/models/pdf.rb
class Pdf < ApplicationRecord
	mount_uploader :image, PdfImageUploader
	extend FriendlyId

	friendly_id :title, use: [:slugged, :finders]
	belongs_to :pdf_category
  default_scope { order(date: :asc)  }

end

app/models/pdf_category.rb
class PdfCategory < ApplicationRecord
	extend FriendlyId
	friendly_id :title, use: [:slugged]

	has_many :pdfs
	scope :not_about, -> { where.not(id: [1, 2]).order(position: :asc) }
end

app/models/text.rb
class Text < ApplicationRecord

end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/video.rb
class Video < ApplicationRecord
  mount_uploader :link_image, LinkImageUploader
  validates_presence_of :title
  default_scope { order(year: :asc) }
end

app/models/work.rb
class Work < ActiveRecord::Base

	extend FriendlyId
	friendly_id :name, use: :slugged
	mount_uploader :overview_img, OverviewUploader
	belongs_to :category
	has_many :infos
	has_many :image_categories, -> { order(position: :asc) }
	has_many :images, through: :image_categories
	has_one :map_info, dependent: :destroy
	# accepts_nested_attributes_for :map_info, reject_if: proc { |attributes| attributes['lat_x'].blank? }
	accepts_nested_attributes_for :map_info, allow_destroy: true
	accepts_nested_attributes_for :image_categories, allow_destroy: true
	accepts_nested_attributes_for :infos, allow_destroy: true

	default_scope { order(position: :asc)}

end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  layout 'works'
  before_action :set_parent_breadcrumb



  def index
    @meta_title = meta_title "Om"
    @meta_description = "Siden 'Om' indeholder Inger og Johannes' personlige tegninger, skitser og historier. Derudover er der i årenes løb blevet produceret en hel del film og artikler om arkitektparret, som også har hjemme her."
    @fact = Fact.last unless Fact.last.nil?
  end

  def artikler
    @meta_title = meta_title "Artikler af andre forfattere"
    @artikler_dansk = Pdf.where(pdf_category_id: [2])
    @artikler_udenlandsk = Pdf.where(pdf_category_id: [1])
    @breadcrumb_child = {title: "Artikler", path: "artikler_path()"}
  end

  def tidslinje
    @meta_title = meta_title "Tidslinje"
    @breadcrumb_child = {title: "Tidslinje", path: "tidslinje_path()"}
  end

  def set_parent_breadcrumb
    @breadcrumb_parent = {title: "Om", path: "om_path()"}
  end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/errors_helper.rb
module ErrorsHelper
end

app/helpers/facts_helper.rb
module FactsHelper
end

app/helpers/pdfs_helper.rb
module PdfsHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/texts_helper.rb
module TextsHelper
end

app/helpers/videoes_helper.rb
module VideoesHelper
end

app/helpers/works_helper.rb
module WorksHelper

  def logged_in_work_helper
    button = (link_to "Rediger værk", edit_work_path(@work), class: "btn btn-secondary")
    content_tag :div, button, class: "col-lg-12"
  end

end

app/views/about/_pagination.html.erb
<div class="next-prev-back-wrapper row">
  <div class="col-md-4 nav-link">
		<% unless prev[:path].empty? %>
			<%= link_to eval(prev[:path]) do %>
				<span class="pagination-arrows prev-work"></span>
				<%= prev[:title] %>
			<% end %>
		<% end %>
  </div>
  <div class="col-md-4 nav-link text-center">
  </div>
  <div class="col-md-4 nav-link text-right">
		<% unless next_w[:path].empty? %>
			<%= link_to eval(next_w[:path]) do %>
				<%= next_w[:title] %>
				<span class="pagination-arrows next-work"></span>
			<% end %>
		<% end %>
  </div>
</div><!-- next-prev-wrapper -->

app/views/about/artikler.html.erb
<% content_for :padding_top_container, "false" %>
<%= render partial: 'about/pagination',
  locals: { prev: { title: 'Håndtegninger', path: "vaerker_path('handtegninger')"},
            next_w: { title: 'Fakta', path: 'facts_path()'} } %>
<h2 class="py-4 text-center">Artikler af andre forfattere</h2>
<div class="row pb-4">
   <%= render partial: "pdf_categories/pdf", collection: @artikler_dansk %>
</div>
<h2 class="py-4 text-center">På andre sprog</h2>
<div class="row pb-4">
   <%= render partial: "pdf_categories/pdf", collection: @artikler_udenlandsk %>
</div>

app/views/about/index.html.erb
<div class="container-fluid"><!-- have no .. -->

  <div class="row">
  <%= link_to vaerker_path('handtegninger'), class: "col-sm-8 om-box" do %>
    <%= image_tag "handtegninger-ny.jpg", class: "image-responsive" %>
  <h2 class=" text-uppercase om-head handtegninger">
    Håndtegninger
  </h2>
  <% end %>
  
  <%= link_to artikler_path(), class: "col-sm-4 om-box" do %>
    <%= image_tag "artikler-ny.jpg", class: "image-responsive" %>
    <h2 class=" text-uppercase om-head">
      Artikler
    </h2>
  <% end %>
  
  
  <% if @fact.nil? %>
    <p> <%= link_to "Opret 'Fakta om Inger og Johannes Exner'", new_fact_path() %> </p>
  <% else %>
    <%= link_to facts_path(), class: "col-sm-4 om-box " do %>
      <%= image_tag "fakta-ny.jpg", class: "image-responsive" %>
      <h2 class=" text-uppercase om-head">
        <%= @fact.title %>
      </h2>
    <% end %>
  <% end %>
  
  <%= link_to vaerker_path('fotos'), class: "col-sm-8 om-box fotos-box" do %>
    <%= image_tag "fotos.jpg", class: "image-responsive" %>
  <h2 class=" text-uppercase fotos om-head">
    Fotos
  </h2>
<% end %>
  


<%= link_to videos_path(), class: "col-sm-8 om-box" do %>
  <%= image_tag 'videos.jpg', class: "image-responsive" %>
  <h2 class=" text-uppercase om-head">
    Video
  </h2>
<% end %>

<%= link_to tidslinje_path(), class: "col-sm-4 om-box tidslinje-box" do %>

  <%= image_tag "tidslinje.jpg", class: "image-responsive" %>
  <h2 class=" text-uppercase tidslinje om-head">
    Tidslinje
  </h2>

<% end %>

<%= link_to vaerker_path("livet-i-tre-huse"), class: "col-sm-12 om-box tre-huse-box" do %>
  <%= image_tag 'tre-huse.jpg', class: "image-responsive" %>

  <h2 class=" text-uppercase tre-huse om-head">
    Livet i tre huse
  </h2>

<% end %>
  
  </div><!-- row -->
<%= link_to "Rediger fakta", edit_fact_path(@fact.id) if user_signed_in? %>
</div>

app/views/about/tidslinje.html.erb
<% content_for :padding_top_container, "false" %>
<%= render partial: 'about/pagination',
  locals: { prev: { title: 'Video', path: 'videos_path()'},
						next_w: { title: 'Livet i tre huse', path: "vaerker_path('livet-i-tre-huse')" } } %>

  <h2 class="text-center">Tidslinje</h2>
  <a href="#" class="to-top" id="toTop"><span class="to-top-text">Til toppen</span></a>
  <% 15.times do |i| %>
    <% i = i + 1 %>
    <% this_image_url = image_url 'tidslinje/' + i.to_s + '_del.jpg' %>
    <%= image_tag this_image_url, class: 'time-line-image img_' + i.to_s%>
  <% end %>

<script>
$(document).ready(function() {
  $(".time-line-image").each(function(image) {
    $(this).on("load", function() {
      $(this).addClass("time-line-image-show"); // transition in about.scss
    });
  });
  $(".to-top").click(function(e) {
    e.preventDefault();
    $(this).removeClass('to-top-show');
    window.scrollTo(0, 0);
  });

});
// GODE GAMLE JAVASCRIPT!
var to_top = document.getElementById('toTop');
var showToTop = function() {
  var y = window.scrollY;
  if (y > window.outerHeight) {
    to_top.classList.add("to-top-show");
  } else {
    to_top.classList.remove("to-top-show");
  }
}

window.addEventListener("scroll", showToTop);
</script>